    @Bean
    public RestTemplate restTemplate(SslBundles sslBundles) throws Exception {

        SslBundle sslBundle = sslBundles.getBundle("client-bundle");

        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(
                sslBundle.getManagers().getKeyManagers(),
                sslBundle.getManagers().getTrustManagers(),
                new SecureRandom()
        );

        CloseableHttpClient httpClient = HttpClients.custom()
                .setSSLContext(sslContext)
                .build();

        return new RestTemplate(
                new HttpComponentsClientHttpRequestFactory(httpClient)
        );
    }
