version: "3.8"
services: 
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      - ./laravel:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - mysql
      - redis
      - artisan
      - npm
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./laravel:/var/www
  mysql:
    image: mysql:5.7
    env_file: 
      - ./mysql.env
  composer:
    build:
      context: .
      dockerfile: ./dockerfiles/composer.dockerfile
    volumes: 
      - ./laravel:/var/www
  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes: 
      - ./laravel:/var/www
    entrypoint: ["php", "/var/www/artisan"]
  npm:
    build:
      context: .
      dockerfile: ./dockerfiles/npm.dockerfile
    volumes: 
      - ./laravel:/var/www
  redis:
    image: redis:6.0.9         

