version: "3.8"
services: 
  server:
    #image: nginx:stable-alpine
    build:
      context: .
      dockerfile: dockerfiles/ngnix.dockerfile
    ports: 
      - '8000:80'
    volumes: 
      - ./laravel:/var/www
      - ./dep-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - mysql
      - redis
  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./laravel:/var/www
  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file: 
      - ./dep-config/mysql.env
  composer:
    container_name: composer
    build:
      context: .
      dockerfile: ./dockerfiles/composer.dockerfile
    volumes: 
      - ./laravel:/var/www
      - /var/www/vendor
  artisan:
    container_name: artisan
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes: 
      - ./laravel:/var/www
    entrypoint: ["php", "/var/www/artisan"]
  npm:
    container_name: npm
    build:
      context: .
      dockerfile: ./dockerfiles/npm.dockerfile
    volumes: 
      - ./laravel:/var/www
      - /var/www/node_modules
  redis:
    image: redis:6.0.9-alpine         

